/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package st.joseph.school.management.system;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;

/**
 *
 * @author hp
 */
public class feeSubmission extends javax.swing.JFrame {

    /**
     * Creates new form feeSubmission
     */
    public feeSubmission() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        id = new javax.swing.JTextField();
        lf = new javax.swing.JTextField();
        mf = new javax.swing.JTextField();
        sf = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        text = new javax.swing.JTextPane();
        jLabel6 = new javax.swing.JLabel();
        af = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        month = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Dutch801 Rm BT", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("FEE COUNTER");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(207, 57, -1, -1));

        jLabel2.setFont(new java.awt.Font("Dutch801 Rm BT", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Annual Fee:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(212, 384, -1, -1));

        jLabel4.setFont(new java.awt.Font("Dutch801 Rm BT", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Sports Fee:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(212, 505, -1, -1));

        jLabel5.setFont(new java.awt.Font("Dutch801 Rm BT", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Monthly Fee:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(212, 571, -1, -1));

        jLabel3.setFont(new java.awt.Font("Dutch801 Rm BT", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Library Fee:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(212, 442, -1, -1));

        id.setFont(new java.awt.Font("Dutch801 Rm BT", 1, 18)); // NOI18N
        id.setForeground(null);
        getContentPane().add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(343, 208, 196, -1));

        lf.setFont(new java.awt.Font("Dutch801 Rm BT", 1, 18)); // NOI18N
        lf.setForeground(null);
        lf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lfActionPerformed(evt);
            }
        });
        getContentPane().add(lf, new org.netbeans.lib.awtextra.AbsoluteConstraints(343, 439, 196, -1));

        mf.setFont(new java.awt.Font("Dutch801 Rm BT", 1, 18)); // NOI18N
        mf.setForeground(null);
        getContentPane().add(mf, new org.netbeans.lib.awtextra.AbsoluteConstraints(343, 568, 196, -1));

        sf.setFont(new java.awt.Font("Dutch801 Rm BT", 1, 18)); // NOI18N
        sf.setForeground(null);
        getContentPane().add(sf, new org.netbeans.lib.awtextra.AbsoluteConstraints(343, 502, 196, -1));

        jButton1.setBackground(new java.awt.Color(255, 204, 51));
        jButton1.setFont(new java.awt.Font("Dutch801 Rm BT", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("PAY");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(472, 633, -1, -1));

        text.setFont(new java.awt.Font("Dutch801 Rm BT", 0, 18)); // NOI18N
        jScrollPane1.setViewportView(text);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(821, 0, 379, 680));

        jLabel6.setFont(new java.awt.Font("Dutch801 Rm BT", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("BACK");
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(343, 637, -1, -1));

        af.setFont(new java.awt.Font("Dutch801 Rm BT", 1, 18)); // NOI18N
        af.setForeground(null);
        getContentPane().add(af, new org.netbeans.lib.awtextra.AbsoluteConstraints(343, 381, 196, -1));

        jLabel7.setFont(new java.awt.Font("Dutch801 Rm BT", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Month Name:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(212, 327, -1, -1));

        jLabel8.setFont(new java.awt.Font("Dutch801 Rm BT", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Id");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(212, 211, 26, -1));

        name.setFont(new java.awt.Font("Dutch801 Rm BT", 1, 18)); // NOI18N
        name.setForeground(null);
        getContentPane().add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(343, 261, 196, -1));

        month.setFont(new java.awt.Font("Dutch801 Rm BT", 1, 18)); // NOI18N
        month.setForeground(null);
        getContentPane().add(month, new org.netbeans.lib.awtextra.AbsoluteConstraints(343, 324, 196, -1));

        jLabel9.setFont(new java.awt.Font("Dutch801 Rm BT", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Student Name");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(212, 264, -1, -1));

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/gold.jpg"))); // NOI18N
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(-30, 40, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lfActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        String ann= af.getText();
        double a= Double.parseDouble(ann);
        String mon= mf.getText();
        double m= Double.parseDouble(mon);
        String lib= lf.getText();
        double l= Double.parseDouble(lib);
        String spo= sf.getText(); //initialize variable for sport fee
        double s= Double.parseDouble(spo); //convert string into double
        String mn= month.getText(); //for month name
        
        double total= a+m+l+s;
        double rem=total-20000; //let's say 20000 is the total fee
        String status;
        if(rem==0){
            status="paid";
        }
        else {
            status="unpaid";
        }
        
        text.setText("\t    Saint Joseph School Management System \n ............................................."
                + "\nTotal Fee to be paid : 20000\n .............................................\n Paid Fee \n\n\n"
                + "Sport FEE: " +spo+"\n Annual FEE: "+ann+"\n Monthly FEE: "+mon+"\n Library FEE: "+lib+
                "\nTotal FEE: "+total+"\n Balance: "+rem);
        
        try{
             Class.forName("com.mysql.jdbc.Driver");
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/sms", "root", "");
            String sql= "insert into fee values (?,?,?,?,?,?,?,?)";
            PreparedStatement ptst = conn.prepareStatement(sql);
            
            ptst.setString(1,id.getText());
            ptst.setString(2,name.getText());
            ptst.setString(3,mn);
            ptst.setDouble(4,a);
            ptst.setDouble(5,l);
            ptst.setDouble(6,s);
            ptst.setDouble(7,m);
            ptst.setString(8,status);
            
            
           ptst.executeUpdate();
           
            JOptionPane.showMessageDialog(null, "Data has been stored successfully!");
            conn.close();
            
            
            
            
        
        } 
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
 
            
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        // TODO add your handling code here:
        welcome obj= new welcome();
        obj.setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel6MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(feeSubmission.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(feeSubmission.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(feeSubmission.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(feeSubmission.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new feeSubmission().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField af;
    private javax.swing.JTextField id;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField lf;
    private javax.swing.JTextField mf;
    private javax.swing.JTextField month;
    private javax.swing.JTextField name;
    private javax.swing.JTextField sf;
    private javax.swing.JTextPane text;
    // End of variables declaration//GEN-END:variables
}
