/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package st.joseph.school.management.system;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;

/**
 *
 * @author hp
 */
public class reportcard extends javax.swing.JFrame {

    /**
     * Creates new form reportcard
     */
    public reportcard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        text = new javax.swing.JTextPane();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        rno = new javax.swing.JTextField();
        name = new javax.swing.JTextField();
        eng = new javax.swing.JTextField();
        kis = new javax.swing.JTextField();
        phy = new javax.swing.JTextField();
        cre = new javax.swing.JTextField();
        d = new javax.swing.JTextField();
        geo = new javax.swing.JTextField();
        bio = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        math = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        bus = new javax.swing.JTextField();
        his = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        frm = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        text.setBackground(new java.awt.Color(0, 153, 204));
        text.setFont(new java.awt.Font("Dutch801 Rm BT", 0, 16)); // NOI18N
        jScrollPane1.setViewportView(text);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(827, 0, 391, 833));

        jLabel1.setFont(new java.awt.Font("Serif", 1, 24)); // NOI18N
        jLabel1.setText("REPORT");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(113, 16, -1, -1));

        jLabel2.setFont(new java.awt.Font("Dutch801 Rm BT", 1, 18)); // NOI18N
        jLabel2.setText("ID");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(113, 57, -1, -1));

        jLabel3.setFont(new java.awt.Font("Dutch801 Rm BT", 1, 18)); // NOI18N
        jLabel3.setText("Roll Number");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(113, 98, -1, -1));

        jLabel4.setFont(new java.awt.Font("Dutch801 Rm BT", 1, 18)); // NOI18N
        jLabel4.setText("Name");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(113, 139, -1, -1));

        jLabel5.setFont(new java.awt.Font("Dutch801 Rm BT", 1, 18)); // NOI18N
        jLabel5.setText("Form");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(113, 181, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("Marks:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(113, 246, 78, -1));

        jLabel7.setFont(new java.awt.Font("Dutch801 Rm BT", 1, 18)); // NOI18N
        jLabel7.setText("English");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 280, -1, -1));

        jLabel8.setFont(new java.awt.Font("Dutch801 Rm BT", 1, 18)); // NOI18N
        jLabel8.setText("Kiswahili");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(113, 324, -1, -1));

        jLabel9.setFont(new java.awt.Font("Dutch801 Rm BT", 1, 18)); // NOI18N
        jLabel9.setText("Physics");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(113, 414, -1, -1));

        jLabel10.setFont(new java.awt.Font("Dutch801 Rm BT", 1, 18)); // NOI18N
        jLabel10.setText("Biology");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(113, 456, -1, -1));

        jLabel11.setFont(new java.awt.Font("Dutch801 Rm BT", 1, 18)); // NOI18N
        jLabel11.setText("CRE");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(113, 497, -1, -1));

        jLabel12.setFont(new java.awt.Font("Dutch801 Rm BT", 1, 18)); // NOI18N
        jLabel12.setText("Geography");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(113, 532, -1, -1));

        jLabel13.setText("......................................................................................................");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(113, 210, -1, -1));

        rno.setFont(new java.awt.Font("Dutch801 Rm BT", 0, 16)); // NOI18N
        getContentPane().add(rno, new org.netbeans.lib.awtextra.AbsoluteConstraints(299, 95, 225, -1));

        name.setFont(new java.awt.Font("Dutch801 Rm BT", 0, 16)); // NOI18N
        getContentPane().add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(299, 139, 225, -1));

        eng.setFont(new java.awt.Font("Dutch801 Rm BT", 0, 16)); // NOI18N
        eng.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                engActionPerformed(evt);
            }
        });
        getContentPane().add(eng, new org.netbeans.lib.awtextra.AbsoluteConstraints(284, 277, 160, -1));

        kis.setFont(new java.awt.Font("Dutch801 Rm BT", 0, 16)); // NOI18N
        getContentPane().add(kis, new org.netbeans.lib.awtextra.AbsoluteConstraints(284, 321, 160, -1));

        phy.setFont(new java.awt.Font("Dutch801 Rm BT", 0, 16)); // NOI18N
        getContentPane().add(phy, new org.netbeans.lib.awtextra.AbsoluteConstraints(284, 411, 160, -1));

        cre.setFont(new java.awt.Font("Dutch801 Rm BT", 0, 16)); // NOI18N
        cre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                creActionPerformed(evt);
            }
        });
        getContentPane().add(cre, new org.netbeans.lib.awtextra.AbsoluteConstraints(284, 494, 160, -1));

        d.setFont(new java.awt.Font("Dutch801 Rm BT", 0, 16)); // NOI18N
        getContentPane().add(d, new org.netbeans.lib.awtextra.AbsoluteConstraints(299, 51, 225, -1));

        geo.setFont(new java.awt.Font("Dutch801 Rm BT", 0, 16)); // NOI18N
        getContentPane().add(geo, new org.netbeans.lib.awtextra.AbsoluteConstraints(284, 529, 160, -1));

        bio.setFont(new java.awt.Font("Dutch801 Rm BT", 0, 16)); // NOI18N
        getContentPane().add(bio, new org.netbeans.lib.awtextra.AbsoluteConstraints(284, 453, 160, -1));

        jButton1.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jButton1.setText("Submit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 620, -1, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 153, 0));
        jLabel14.setText("BACK");
        jLabel14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel14MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(732, 23, -1, -1));

        jLabel15.setFont(new java.awt.Font("Dutch801 Rm BT", 1, 18)); // NOI18N
        jLabel15.setText("Maths");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(113, 366, -1, -1));

        math.setFont(new java.awt.Font("Dutch801 Rm BT", 0, 16)); // NOI18N
        getContentPane().add(math, new org.netbeans.lib.awtextra.AbsoluteConstraints(284, 363, 160, -1));

        jLabel16.setFont(new java.awt.Font("Dutch801 Rm BT", 1, 18)); // NOI18N
        jLabel16.setText("History");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(113, 574, -1, -1));

        jLabel17.setFont(new java.awt.Font("Dutch801 Rm BT", 1, 18)); // NOI18N
        jLabel17.setText("Business");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(113, 615, -1, -1));

        bus.setFont(new java.awt.Font("Dutch801 Rm BT", 0, 16)); // NOI18N
        getContentPane().add(bus, new org.netbeans.lib.awtextra.AbsoluteConstraints(284, 613, 160, -1));

        his.setFont(new java.awt.Font("Dutch801 Rm BT", 0, 16)); // NOI18N
        his.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hisActionPerformed(evt);
            }
        });
        getContentPane().add(his, new org.netbeans.lib.awtextra.AbsoluteConstraints(284, 571, 160, -1));

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/resu.jpg"))); // NOI18N
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 230, -1, -1));

        frm.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        frm.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", " " }));
        getContentPane().add(frm, new org.netbeans.lib.awtextra.AbsoluteConstraints(299, 177, 225, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        try{
             Class.forName("com.mysql.jdbc.Driver");
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/sms", "root", "");
            String sql= "insert into report values(?,?,?,?,?,?,?,?,?,?,?,?,?,?)";
            String e= eng.getText();
            double a1= Double.parseDouble(e);
             String k= kis.getText();
            double a2= Double.parseDouble(k);
             String m= math.getText();
            double a3= Double.parseDouble(m);
             String p= phy.getText();
            double a4= Double.parseDouble(p);
             String b= bio.getText();
            double a5= Double.parseDouble(b);
             String c= cre.getText();
            double a6= Double.parseDouble(c);
            String g= geo.getText();
            double a7= Double.parseDouble(g);
            String h= his.getText();
            double a8= Double.parseDouble(h);
            String bs= bus.getText();
            double a9= Double.parseDouble(b);
            
            
            double total= ((a1+a2+a3+a4+a5+a6+a7+a8+a9)*100)/900;
            
            String grade;
            
            if(total>=80){
                grade= "A+";
            }
            else if(total>=70 && total<80){
            grade ="A";
            }
            
            else if(total>=60 && total<70){
            grade ="B";
            }
            
            else if(total>=50 && total<60){
            grade ="C";
            }
            
            else if(total>=40 && total<50){
            grade ="D";
            }
            
            else {
                grade="Fail";
            }
            
           
            String r= rno.getText();
            String n= name.getText();
            String form= frm.getSelectedItem().toString();
            String en= eng.getText();
            String ki= kis.getText();
            String ma= math.getText();
            String ph= phy.getText();
            String bi= bio.getText();
            String cr= cre.getText();
            String ge= geo.getText();
            String hi= his.getText();
            String bu= bus.getText();
            
            PreparedStatement ptst= conn.prepareStatement(sql);
            ptst.setString(1, d.getText());
            ptst.setString(2, r);
            ptst.setString(3, n);
            ptst.setString(4, form);
            ptst.setString(5, en);
            ptst.setString(6, ki);
            ptst.setString(7, ma);
            ptst.setString(8, ph);
            ptst.setString(9, bi);
            ptst.setString(10, cr);
            ptst.setString(11, ge);
            ptst.setString(12, hi);
            ptst.setString(13, bu);
            ptst.setString(14, grade);
            
            ptst.executeUpdate();
            JOptionPane.showMessageDialog(null, "Data has been saved");
            
            text.setText("REPORT CARD\n\n Roll Number: "+r+"\nStudent Name: "+n+"\nForm: "+form+"\n\n......................................\nMarks\n\nEnglish: "+en+"\nKiswahili:"+ki+"\nMaths: "+ma+"\nPhysics: "+ph+" \nBiology:"+bi+"\nCRE: "+cr+" \nGeography: "+ge+" \nHistory:"+hi+"\nBusiness:"+bu+"\nGrade: "+grade);
            conn.close();
            
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jLabel14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MouseClicked
        // TODO add your handling code here:
        welcome obj= new welcome();
        obj.setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel14MouseClicked

    private void creActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_creActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_creActionPerformed

    private void hisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hisActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_formComponentShown

    private void engActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_engActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_engActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(reportcard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(reportcard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(reportcard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(reportcard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new reportcard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField bio;
    private javax.swing.JTextField bus;
    private javax.swing.JTextField cre;
    private javax.swing.JTextField d;
    private javax.swing.JTextField eng;
    private javax.swing.JComboBox<String> frm;
    private javax.swing.JTextField geo;
    private javax.swing.JTextField his;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField kis;
    private javax.swing.JTextField math;
    private javax.swing.JTextField name;
    private javax.swing.JTextField phy;
    private javax.swing.JTextField rno;
    private javax.swing.JTextPane text;
    // End of variables declaration//GEN-END:variables
}
